# -*- coding: utf-8 -*-
"""MSDA683 Lab4 Jepson

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13qkpIAllAzkLIiDST6v41tJLKmwNJPbP
"""

import pandas as pd
import spacy
nlp = spacy.load('en_core_web_sm')
import time
import re
from collections import Counter
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv('/content/drive/MyDrive/MSDA683/HW3/Reviews.csv')

df.head()

print(df.keys())

df.shape

df.info()

rating_df = pd.DataFrame(df, columns=['Score','Text'])
print(rating_df.shape)
rating_df.head()

print(rating_df.keys())

rating_df.info()

rating_df.Score.value_counts()

rating_df.Score.value_counts().plot(kind='bar')
plt.savefig('/content/drive/MyDrive/MSDA683/QuantDistValues.jpg', bbox_inches='tight')

def remove_urls(text):
    url_pattern = re.compile(r'https?://\S+|www\.\S+')
    return url_pattern.sub(r'', text)

rating_df['Text'] = rating_df['Text'].apply(lambda text: remove_urls(text))
rating_df.head()

import string
PUNCT_TO_REMOVE = string.punctuation
def remove_punctuation(text):
    return text.translate(str.maketrans('', '', PUNCT_TO_REMOVE))

rating_df['Text'] = rating_df['Text'].apply(lambda text: remove_punctuation(text))
rating_df.head()

fiveStardf = rating_df[df['Score'] == 5]

fiveStardf.head()

fiveStarSamp = fiveStardf.sample(n=50000)
fiveStarSamp.shape

start_time = time.perf_counter()
FiveStarAdj = []
FiveStarProds = []
for index, row in fiveStarSamp.iterrows():
  doc = nlp(row['Text'])
  for ent in doc.ents:
    if ent.label_ == 'PRODUCT':
      FiveStarProds.append(str(ent).lower().capitalize())
  for token in doc:
    if token.pos_ == 'ADJ':
      FiveStarAdj.append(str(token).capitalize())
end_time = time.perf_counter()
print(f"Elapsed time: {end_time - start_time} seconds")
print(f"Found {len(FiveStarProds)} brands mentioned in {len(fiveStarSamp)} reviews" )

sorted_Prodlist = sorted(FiveStarProds, key=str)
 top_Prodlist = pd.DataFrame(Counter(sorted_Prodlist).most_common(20), columns=['Product','Count'])
 print(top_Prodlist)

final_list = top_Prodlist

final_list = final_list.drop(index=14)

print(final_list)

plot = final_list.plot.barh(x='Product', y='Count',
                            title='Common Products Mentioned in 5-Star Reviews').invert_yaxis()
plt.savefig('/content/drive/MyDrive/MSDA683/5starBrands.jpg', bbox_inches='tight')

sorted_Adjlist = sorted(FiveStarAdj, key=str)
top_Adjlist = pd.DataFrame(Counter(sorted_Adjlist).most_common(20), columns=['Adjective','Count'])
print(top_Adjlist)

plot = top_Adjlist.plot.barh(x='Adjective', y='Count', color = 'green',
                            title='Common Adjectives Mentioned in 5-Star Reviews').invert_yaxis()
plt.savefig('/content/drive/MyDrive/MSDA683/5starADJ.jpg', bbox_inches='tight')

start_time = time.perf_counter()
FiveStarAdjOne = []
for index, row in fiveStarSamp.iterrows():
  doc = nlp(row['Text'])
  for ent in doc.ents:
    if ent.label_ == 'PRODUCT' and str(ent).lower() == "diet coke":
      for token in doc:
        if token.pos_ == 'ADJ':
          FiveStarAdjOne.append(str(token).capitalize())
end_time = time.perf_counter()
print(f"Elapsed time: {end_time - start_time} seconds")
print(FiveStarAdjOne)

sorted_AdjlistOne = sorted(FiveStarAdjOne, key=str)
top_AdjlistOne = pd.DataFrame(Counter(sorted_AdjlistOne).most_common(20), columns=['Adjective','Count'])
print(top_AdjlistOne)

plot = top_AdjlistOne.plot.barh(x='Adjective', y='Count', color = 'green',
                            title='Common Adjectives Mentioned in 5-Star Diet Coke Reviews').invert_yaxis()
plt.savefig('/content/drive/MyDrive/MSDA683/dietcoke5starADJ.jpg', bbox_inches='tight')